name: GameCI Template 🎮

on: workflow_dispatch

jobs:
  buildWebGL:
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: github.ref == 'refs/heads/test'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENCE }}
        with:
          targetPlatform: StandaloneLinux64
          projectPath: ./Server