name: GameCI Template 🎮

on: push

jobs:
  build:
    testRunner:
      name: Test-Runner
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/test'
      strategy:
        fail-fast: false
        matrix:
          testMode:
            - EditMode
            - PlayMode
      steps:
        - name: Build
          uses: game-ci/unity-builder@v4
          env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          with:
            targetPlatform: StandaloneLinux64
            projectPath: Client